version: '3.4'

services:
  cloudpatternsapi:
    image: ${DOCKER_REGISTRY-}cloudpatternsapi
    build:
      context: .
      dockerfile: cloudpatternsapi/Dockerfile
    ports:
      - 7266:443

  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
